version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "actions/*"
      my-actions:
        patterns:
          - "xt0rted/*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      analyzers:
        patterns:
          - "IDisposableAnalyzers"
          - "Roslynator.*"
      testing:
        patterns:
          - "GitHubActionsTestLogger"
          - "Microsoft.NET.Test.Sdk"
          - "Shouldly"
          - "xunit"
          - "xunit.*"
