name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write

env:
  DOTNET_NOLOGO: true
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.0

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=beta.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: |
            3.1.x
            5.0.x
            6.0.x

      #- name: Set up .NET Core (global.json)
      #  uses: actions/setup-dotnet@v2.0.0

      - run: npm ci

      - run: dotnet tool restore

      - run: dotnet r build:release

      - run: dotnet r test:release

      - run: dotnet r pack:release -- --version-suffix $VERSION_SUFFIX

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          path: ./artifacts/*.nupkg

      - name: Upload test results
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: test-results
          path: ./.coverage/*.trx

      - name: Publish to GPR
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}
