name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CONFIGURATION: Release
  DOTNET_NOLOGO: true
  FORCE_COLOR: 3

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.4

      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .nvmrc

      - uses: xt0rted/markdownlint-problem-matcher@v3.0.0

      - run: npm ci

      - run: npm test

  build:
    needs: lint-markdown

    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.4

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=beta.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .nvmrc

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.5.0

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          colored-output: false
          strip-comments-from-global-json: false
          dotnet-version: |
            6.0.x

      - run: npm ci

      - run: dotnet tool restore

      - run: dotnet r build

      - run: dotnet r test -- --no-build --logger GitHubActions

      - run: dotnet r pack -- --no-build --version-suffix $VERSION_SUFFIX

      - name: Publish artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          path: ./artifacts/*.nupkg

      - name: Publish to GPR
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}
