name: CI

on:
  push:
    branches: [main]

permissions:
  packages: write

env:
  DOTNET_NOLOGO: true
  NODE_VERSION: "15.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=beta.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Setup Node
        uses: actions/setup-node@v2.3.1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup .NET Core (3.1.x)
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: "3.1.x"

      - name: Setup .NET Core (global.json)
        uses: actions/setup-dotnet@v1.8.1

      - run: npm ci

      - run: dotnet build --configuration Release

      - run: dotnet test --configuration Release --no-build

      - run: dotnet pack --configuration Release --output ./artifacts --version-suffix $VERSION_SUFFIX

      - name: Publish artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          path: ./artifacts/*.nupkg

      - name: Publish to GPR
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}
