name: .NET SDK updater

on:
  schedule:
    - cron: "0 12 * * 1-5"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.DOTNET_SDK_UPDATER_APP_ID }}
          private_key: ${{ secrets.DOTNET_SDK_UPDATER_PRIVATE_KEY }}

      - name: Check out repo
        uses: actions/checkout@v2.4.0

      - name: Check for new sdk version
        uses: xt0rted/dotnet-sdk-updater@v1.0.0
        id: sdk

      - name: Security update check
        if: steps.sdk.outputs.updated == 'true'
        id: security
        shell: bash
        run: |
          if [ "${{ steps.sdk.outputs.security-release }}" = "true" ]
          then
            echo "::set-output name=label::security"
            echo "::set-output name=message::**This update includes a security fix.**"
          fi

      - name: Create pull request
        if: steps.sdk.outputs.updated == 'true' && steps.sdk.outputs.dry-run == 'false'
        id: cpr
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          token: ${{ steps.generate_token.outputs.token }}
          author: dotnet-sdk-updater[bot] <100138291+dotnet-sdk-updater[bot]@users.noreply.github.com>
          signoff: true
          committer: dotnet-sdk-updater[bot] <100138291+dotnet-sdk-updater[bot]@users.noreply.github.com>
          commit-message: |
            Bump dotnet sdk from ${{ steps.sdk.outputs.updated-version-from }} to ${{ steps.sdk.outputs.updated-version-to }}

            Bump dotnet sdk from ${{ steps.sdk.outputs.updated-version-from }} to ${{ steps.sdk.outputs.updated-version-to }}. ${{ steps.security.outputs.message }}

            - [Release notes](https://github.com/dotnet/core/releases/tag/v${{ steps.sdk.outputs.updated-version-to }})
            - [Changelog](${{ steps.sdk.outputs.release-notes }})

            ---
            updated-dependencies:
            - dependency-name: dotnet-sdk
              dependency-type: direct:production
              update-type: version-update:${{ steps.sdk.outputs.update-type }}
            ...
          branch: "dependabot/nuget/dotnet-sdk-${{ steps.sdk.outputs.updated-version-to }}"
          delete-branch: true
          title: |
            Bump dotnet sdk from ${{ steps.sdk.outputs.updated-version-from }} to ${{ steps.sdk.outputs.updated-version-to }}
          body: |
            Bumps [dotnet sdk](https://github.com/dotnet/sdk) from ${{ steps.sdk.outputs.updated-version-from }} to ${{ steps.sdk.outputs.updated-version-to }}. ${{ steps.security.outputs.message }}

            - [Release notes](https://github.com/dotnet/core/releases/tag/v${{ steps.sdk.outputs.release-version }})
            - [Changelog](${{ steps.sdk.outputs.release-notes }})
          labels: |
            dependencies
            .NET
            ${{ steps.security.outputs.label }}
