name: Pull Request

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CONFIGURATION: Release
  DOTNET_NOLOGO: true
  FORCE_COLOR: 3

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5.0.0

      - name: Install Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: .nvmrc

      - uses: xt0rted/markdownlint-problem-matcher@v3.0.0

      - run: npm ci

      - run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5.0.0

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=alpha.${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: .nvmrc

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.5.0

      - name: Set up .NET
        uses: xt0rted/setup-dotnet@v1.5.0
        with:
          colored-output: false
          strip-comments-from-global-json: false
          dotnet-version: |
            6.0.x

      - run: npm ci

      - run: dotnet tool restore

      - run: dotnet r build

      - run: dotnet r test -- --no-build --logger GitHubActions

      - run: dotnet r pack -- --no-build --version-suffix $VERSION_SUFFIX

      - name: Publish artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          path: ./artifacts/*.nupkg
