name: Pull Request

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOTNET_NOLOGO: true
  FORCE_COLOR: 3
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.0.2

      - name: Build version suffix
        run: echo "VERSION_SUFFIX=alpha.${{ github.event.number }}" >> $GITHUB_ENV

      - name: Set up Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
        env:
          FORCE_COLOR: 0

      - name: Set up .NET Core
        uses: xt0rted/setup-dotnet@v1.4.0

      - run: npm ci

      - run: dotnet tool restore

      - run: dotnet r build:release

      - run: dotnet r test:release

      - run: dotnet r pack:release -- --version-suffix $VERSION_SUFFIX

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          path: ./artifacts/*.nupkg

      - name: Upload test results
        uses: actions/upload-artifact@v2.3.1
        if: always()
        with:
          name: test-results
          path: ./.coverage/*.trx
